config/routes.rb
Rails.application.routes.draw do
  root 'scans#index'
  resources :scans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scan.rb
class Scan < ApplicationRecord
  enum status: [:queued, :running, :finished]
  validates :title, presence: true
  validates :target, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController

  def index
    @scan ||= Scan.new
    
    respond_to do |format|
      format.json { render json: ScansDatatable.new(view_context) }
      format.html
    end
  end

  def show
    @scan = Scan.find(params[:id])
    @result = redis.get(@scan.id)
  end

  def new
    @scan ||= Scan.new
  end

  def create
    @scan = Scan.new(scan_params)

    if @scan.save
      @scan.update(jid: HellraiserWorker.perform_async(@scan.id))
    else
      render 'new'
    end

    respond_to :js
  end

  def update
    @scan = Scan.find(params[:id])
    @scan.queued!
    @scan.update(jid: HellraiserWorker.perform_async(@scan.id))
    respond_to :js
  end

  def destroy
    @scan = Scan.find(params[:id])

    if @scan.finished?
      FileUtils.rm Dir.glob(HellRaiser.configuration.output_dir + @scan.id.to_s + '.*')
      redis.del @scan.id
      @scan.destroy
    else
      HellraiserWorker.cancel!(@scan.jid)
      @scan.finished!
    end

    respond_to :js
  end

  private

  def scan_params
    params.require(:scan).permit(:title, :target)
  end

  def redis
    @redis ||= Redis.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scans_helper.rb
module ScansHelper
end

app/views/application/_banner.html.erb
<pre id="banner" style="letter-spacing: -0.11em;">
  ___ ___         .__  .__ __________        .__
 /   |   \   ____ |  | |  |\______   \_____  |__| ______ ___________
/    ~    \_/ __ \|  | |  | |       _/\__  \ |  |/  ___// __ \_  __ \
\    Y    /\  ___/|  |_|  |_|    |   \ / __ \|  |\___ \\  ___/|  | \/
 \___|_  /  \___  >____/____/____|_  /(____  /__/____  >\___  >__|
       \/       \/                 \/      \/        \/     \/
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HellRaiser</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => "reload" %>
    <%= tag :meta, name: 'turbolinks-cache-control', content: 'no-cache' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/scans/_form.html.erb
<%= form_for @scan, remote: true, html: {class: 'form-inline', style: 'display:inline'} do |f| %>

  <div class="form-group">
    <%= f.text_field :title, placeholder: 'Scan Title', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.text_field :target, placeholder: 'Target IP Address',  class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.button icon('flag-checkered', 'Start'), class: 'btn btn-md btn-default' %>
  </div>
<% end %>

app/views/scans/create.js.erb
$('#header a').show()
$('#header form').remove()
$('.datatable').DataTable().draw()

app/views/scans/destroy.js.erb
$('.datatable').DataTable().draw()

app/views/scans/index.html.erb
<h1 class="page-header">
  <div class="container-fluid header-container" >
    <div class="row">
      <div class="col-lg-6 col-xs-12">
        <%= render 'banner' %>
      </div>
      <div id="form" class="col-lg-6 col-xs-12 text-right header-buttons">
        <%= render 'scans/form' %>
      </div>
    </div>
  </div>
</h1>

<table class="table table-responsive datatable" data-api="<%= scans_path(format: :json) %>">
  <thead>
    <tr>
      <th>Title</th>
      <th>Target</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/scans/new.js.erb
$('#form a').hide()
$('#form form').remove()
$('#form').append('<%= j render 'form' %>')
$('.field_with_errors').change(function() {
  $(this).removeClass('field_with_errors')
})

app/views/scans/show.html.erb
<h1 class="page-header">
  <div class="container-fluid header-container" >
    <div class="row">
      <div class="col-xs-6">
        <%= render 'banner' %>
      </div>
      <div class="col-xs-6 text-right header-buttons">
        <%= link_to 'Back', root_path, class: 'btn btn-lg btn-default' %>
      </div>
    </div>
  </div>
</h1>

<p>
  <strong>Title:</strong>
  <%= @scan.title %>
</p>

<p>
  <strong>Target:</strong>
  <%= @scan.target %>
</p>

<p>
  <strong>Status:</strong>
  <%= @scan.status.titleize %>
</p>

<% if @result and File.exist? @result %>
  <p>
  <% file = File.read(@result) %>
  <% scans = JSON.parse(file) %>
  <% id = 0 %>
  <% scans.each do |scan| %>
    <table>
      <tr>
        <td>IP Address:</td>
        <td> <%= scan['ip'] %></td>
      </tr>
      <tr>
        <td>Status:</td>
        <td> <%= scan['status']['state'] %></td>
      </tr>
      <tr>
        <td>MAC:</td>
        <td> <%= scan['mac'] %></td>
      </tr>
      <tr>
        <td>Vendor:</td>
        <td> <%= scan['vendor'] %></td>
      </tr>
      <tr>
        <td>Hostnames:</td>
        <td>
          <% scan['hostnames'].each do |h| %>
            <%= h['name'] %>
          <% end %>
        </td>
      </tr>
    </table>
    Operation System:
    <% if scan['cpes'] %>
      <% scan['cpes'].each do |(cpe,cves)| %>
        <% if cves.count > 0 %>
          <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
          <a data-toggle="collapse" href="#<%= cpe_id %>"><%= cpe %></a>
        <% else %>
          <%= cpe %>
        <% end %>
      <% end %>
      <% scan['cpes'].each do |(cpe,cves)| %>
        <% if cves.count > 0 %>
          <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
          <div id="<%= cpe_id %>" class="collapse">
          <%= cpe %>
          <% cves.each do |cve| %>
            <div>
            <%= link_to cve['id'], cve['idurl'] %>
            <% if cve['impact'] %>
              <% if cve['impact']['confidentiality'] == "COMPLETE" %>
                <span style="color:red" title="Confidentiality Impact: COMPLETE">
              <% elsif cve['impact']['confidentiality'] == "PARTIAL" %>
                <span style="color:orange" title="Confidentiality Impact: PARTIAL">
              <% elsif cve['impact']['confidentiality'] == "NONE" %>
                <span style="color:green" title="Confidentiality Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              C
              </span>
              <% if cve['impact']['integrity'] == "COMPLETE" %>
                <span style="color:red" title="Integrity Impact: COMPLETE">
              <% elsif cve['impact']['integrity'] == "PARTIAL" %>
                <span style="color:orange" title="Integrity Impact: PARTIAL">
              <% elsif cve['impact']['integrity'] == "NONE" %>
                <span style="color:green" title="Integrity Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              I
              </span>
              <% if cve['impact']['availability'] == "COMPLETE" %>
                <span style="color:red" title="Availability Impact: COMPLETE">
              <% elsif cve['impact']['availability'] == "PARTIAL" %>
                <span style="color:orange" title="Availability Impact: PARTIAL">
              <% elsif cve['impact']['availability'] == "NONE" %>
                <span style="color:green" title="Availability Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              A
              </span>
            <% end %>
            <% if cve['access'] %>
              <%= image_tag(cve['access']['vector'] + ".png", width: "20", height: "20", title: "ACCESS: " + cve['access']['vector']) %>
            <% end %>
            <% if cve['edb'] %>
              <%= link_to image_tag("edb.png", width: "20", height:"20", title: "Exploit-DB"), cve['edb'] %>
            <% end %>
            <% if cve['msf'] %>
              <%= link_to image_tag("msf.png", width: "20", height:"20", title: "Metasploit"), cve['msf'] %>
            <% end %>
            </div>
          <% end %>
        <% end %>
        </div>
      <% end %>
    <% else %>
      System not reconized
    <% end %>
    <% id = id+1 %>
    <% if scan['ports'] %>
      <table class="table table-bordered">
      <thead>
        <tr>
          <th>Service</th>
          <th>Banner</th>
          <th>Port/Protocol</th>
          <th>Status</th>
          <th>CPEs</th>
        </tr>
      </thead>
      <% scan['ports'].each do |port| %>
        <tr>
          <td><%= port['name'] %></td>
          <td><%= port['product'] %> <%= port['version'] %> <%= port['extra_info'] %></td>
          <td><%= port['port'] %>/<%= port['protocol'] %></td>
          <td><%= port['state'] %></td>
          <td>
            <% port['cpes'].each do |(cpe,cves)| %>
              <% if cves.count > 0 %>
                <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
                <a data-toggle="collapse" href="#<%= cpe_id %>"><%= cpe %></a>
              <% else %>
                <%= cpe %>
              <% end %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td colspan="5">
          <% port['cpes'].each do |(cpe,cves)| %>
            <% if cves.count > 0 %>
              <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
              <div id="<%= cpe_id %>" class="collapse">
              <%= cpe %>
              <% cves.each do |cve| %>
                <div>
                <%= link_to cve['id'], cve['idurl'] %>
                <% if cve['impact'] %>
                  <% if cve['impact']['confidentiality'] == "COMPLETE" %>
                    <span style="color:red" title="Confidentiality Impact: COMPLETE">
                  <% elsif cve['impact']['confidentiality'] == "PARTIAL" %>
                    <span style="color:orange" title="Confidentiality Impact: PARTIAL">
                  <% elsif cve['impact']['confidentiality'] == "NONE" %>
                    <span style="color:green" title="Confidentiality Impact: NONE">
                  <% else %>
                    <span style="color:black">
                  <% end %>
                  C
                  </span>
                  <% if cve['impact']['integrity'] == "COMPLETE" %>
                    <span style="color:red" title="Integrity Impact: COMPLETE">
                  <% elsif cve['impact']['integrity'] == "PARTIAL" %>
                    <span style="color:orange" title="Integrity Impact: PARTIAL">
                  <% elsif cve['impact']['integrity'] == "NONE" %>
                    <span style="color:green" title="Integrity Impact: NONE">
                  <% else %>
                    <span style="color:black">
                  <% end %>
                  I
                  </span>
                  <% if cve['impact']['availability'] == "COMPLETE" %>
                    <span style="color:red" title="Availability Impact: COMPLETE">
                  <% elsif cve['impact']['availability'] == "PARTIAL" %>
                    <span style="color:orange" title="Availability Impact: PARTIAL">
                  <% elsif cve['impact']['availability'] == "NONE" %>
                    <span style="color:green" title="Availability Impact: NONE">
                  <% else %>
                    <span style="color:black">
                  <% end %>
                  A
                  </span>
                <% end %>
                <% if cve['access'] %>
                  <%= image_tag(cve['access']['vector'] + ".png", width: "20", height: "20", title: "ACCESS: " + cve['access']['vector']) %>
                <% end %>
                <% if cve['edb'] %>
                  <%= link_to image_tag("edb.png", width: "20", height:"20", title: "Exploit-DB"), cve['edb'] %>
                <% end %>
                <% if cve['msf'] %>
                 <%= link_to image_tag("msf.png", width: "20", height:"20", title: "Metasploit"), cve['msf'] %>
                <% end %>
                </div>
              <% end %>
            <% end %>
            </div>
          <% end %>
          </td>
        </tr>
        <% id = id+1 %>
      <% end %>
      </table>
    <% end %>
  <% end %>
<% end %>

app/views/scans/update.js.erb
$('.datatable').DataTable().draw()